### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by muschellij2** [dipterix/ravetools#9]
Archived April 18, 2024 - unsure if this is expected: https://cran.r-project.org/web/packages/ravetools/index.html

**Comment by dipterix** [comment]
Hi @muschellij2 

Thanks for asking. Package `ravetools` (toolbox functions), `raveio` (file IO and pipeline frameworks), `threeBrain` (WebGL viewer), `ravedash` (shiny dashboard) are all under the same project. I personally have spent 7 years developing these packages with CRAN standard (at least I tried to abide by their policy). I have done my best to make them back on CRAN, but unfortunately there is nothing I could do w.r.t. how long it will take for CRAN to process these packages.

My alternative plan is to submit them to Bioconductor.

**Comment by muschellij2** [comment]
Fully understood - I was just giving an FYI because I've had packages fall through the cracks, but this seems different.

**Comment by dipterix** [comment]
I really appreciate it. I really like R but it's a struggle to submit packages to CRAN. Even if (say, one day) we decide not to be on CRAN, the package will continue to be developed and the CRAN standard/policy will be reinforced. Fortunately, with the help of `r-universe`, lots of packages don't have to be on CRAN to be (cross) compiled.
